### ISSUE TITLE
Adhere to keepchangelog.com format

### ISSUE THREAD

**Issue by Sobak** [fojuth/readmegen#13]
Just a little suggestion - while there is no the-only-one, official and shiny standard describing how changelog should be formated, one proposed by [keepchangelog.com](http://keepachangelog.com/) seems to be most popular. Maybe it would be good to adhere to it? Current format could be still preserved by commandline option/switch/however you call it.

Cheers.

**Comment by fojuth** [comment]
Hey, thanks for the tip. I'll look into it and see what develops. Maybe I'll adhere to these rules, can't say for sure at the moment. Still, thanks again :)
