### ISSUE TITLE
Problem in Conventional commit compatibility with scope

### ISSUE THREAD

**Issue by ingluife** [fojuth/readmegen#24]
Hi, @fojuth. I have a problem with the use of this package.

I use the Conventional Commit standard for write my history log in my project. However, this package ignore all commits that has a **scope**. For example:

- feat(**login**): Add user login functionality

This commit is ignored by the package.

I check the package and i found a solution: Change the regular expression that evaluate the commit structure.

- Solution: In the /src/Log/Extractor.php file, I edit the return of getPattern method.

 `return '/(^('.$keywords.')?\([^()]*[^()]*\):)|(^('.$keywords.'):)/i';`

This solution accept both structures:

>  feat: Add user login functionality

> feat(**login**): Add user login functionality

**Comment by fluchi** [comment]
Hi @ingluife,
this is a good feature, thanks for suggesting and point out the solution.
Felipe

**Comment by ingluife** [comment]
Hi Felipe. Do you want that I create a PR for this?

**Comment by fluchi** [comment]
Hi @ingluife,
sorry, I should've told you that I already implemented the feature you suggested.
thanks
Felipe

**Comment by ingluife** [comment]
Fixed
